name: Sync with Codeberg

on:
  schedule:
    - cron: '0 * * * *' # Runs every hour, adjust as needed
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set credentials
        run: |
          git config --global user.name "GH_bot"
          git config --global user.email "your.email@example.com"

      - name: Pull changes from Codeberg
        run: |
          git remote add codeberg https://codeberg.org/metalfoxdev/juststudy-site.git
          git fetch codeberg
          git merge codeberg/main --allow-unrelated-histories -m "Merge from Codeberg"

      - name: Push changes to GitHub
        run: |
          git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
